[system]
description = "Create and execute a checkpoint for the test_component"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "test_component"
img  = "tests.chkpt"
deps = [{srv = "booter", interface = "init"}]
baseaddr = "0x1600000"
constructor = "booter"